name: GitHub PR
run-name: PR comment
on:
  pull_request:
    branches: [main]

jobs:
  comment:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install

      - name: Get branch name
        id: branch
        run: |
          branch_name=${{ github.base_ref }}
          echo "Branch name: $branch_name"

      - name: Set merge method
        id: set-merge-method
        run: |
          if [ "$branch_name" == "main" ]; then
            merge_method="squash"
          else
           merge_method="rebase"
          fi
          echo "Merge method: $merge_method"


      - name: Comment on PR
        uses: actions/github-script@v5
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const targetBranch = context.payload.pull_request.base.ref;
            const comment = `
            대상 브랜치의 이름이 ${targetBranch}로 지정되었습니다.
            <!-- Your custom comment goes here -->
            `;
            
            context.pull_request.
            
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: comment
            });
    
