name: GitHub PR
run-name: PR comment
on:
  pull_request:
    branches: [main]

jobs:
  comment:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install

      - name: Comment on PR
        uses: unsplash/comment-on-pr@v1
        with:
          message: |
            Hello! Thank you for opening this pull request.
            <!-- Your custom comment goes here -->
          repo-token: ${{ secrets.GITHUB_TOKEN }}
    
